name: ci_macos

env:
    HOMEBREW_NO_INSTALL_CLEANUP: 1
    CTEST_NO_TESTS_ACTION: error
    CTEST_PARALLEL_LEVEL: 0
    CMAKE_BUILD_PARALLEL_LEVEL: 4

on:
  push:
    paths:
    - "**.f90"
    - "**.F90"
    - "**.c"
    - "**.cpp"
    - "**.cmake"
    - "**/CMakeLists.txt"
    - ".github/workflows/ci_macos.yml"
    - ".github/workflows/composite-unix/**"

jobs:

  mac:
    # need Apple Silicon for exception handling try_compile detection to work
    runs-on: macos-14
    timeout-minutes: 10

    strategy:
      matrix:
        c: [{cc: clang, cxx: clang++}, {cc: gcc-13, cxx: g++-13}]

    env:
      FC: gfortran-13
      CC: ${{ matrix.c.cc }}
      CXX: ${{ matrix.c.cxx }}

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/workflows/composite-unix
